config/routes.rb
Rails.application.routes.draw do

# ============== spots ======================
  resources :spots
# ============== spots ======================

# ============== posts ======================
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
# ============== posts ======================

# ============== users ======================
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
    post 'users/guest_login', to: 'users/sessions#guest_login'
  end

  resources :users do
    member do
      get 'profile'
    end
  end
# ============== users ======================
  root to: 'home#index'
end

app/models/spot.rb
class Spot < ApplicationRecord
  # イメージカラムを指定
  has_one_attached :spot_image

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  #アソシエーション設定
  belongs_to :user
  has_many :spot_category_relations
  has_many :categories, through: :spot_category_relations

  # ransackモデルにホワイトリストを登録
  def self.ransackable_attributes(auth_object = nil)
    ["address"]
  end

  validates :title, presence: true, length: { maximum: 15 }
  validates :address, presence: true
  validates :spot_image, presence: true
  validates :content, length: { maximum: 150 }
  validates :user_id, presence: true
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q, only: [:index]

  def index
    @spots = @q.result.with_attached_spot_image.includes(:categories, :spot_category_relations).page(params[:page]).per(12).order(created_at: :desc)
    @categories = Category.all
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @spots = @category.spots.page(params[:page]).per(12).order(created_at: :desc)
    end
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      flash[:notice] = "#{@spot.user.name}さんのスポット投稿が完了しました。"
      redirect_to spots_path
    else
      render "new"
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      flash[:notice] = "#{@spot.user.name}さんの投稿を更新しました"
      redirect_to spots_path
    else
      render "edit"
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to spots_path
    flash[:notice] = "#{@spot.user.name}さんの投稿を削除しました"
  end

  private

  def spot_params
    params.require(:spot).permit(:title, :content, :address, :latitude, :longitude, :spot_image, :user_id, category_ids: [])
  end

  def set_q
    @q = Spot.ransack(params[:q])
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/edit.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "投稿一覧", spots_path %></li>
      <li class="breadcrumb-item"><%= link_to "スポット投稿", spot_path(@spot) %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "スポット編集", edit_spot_path %></li>
    </ol>
  </nav>
  <div class="spot-edit">
    <div class="spot-edit-title">
      <h1>Edit Spot</h1>
      <p>スポット編集</p>
    </div>
    <div class="spot-edit-form">
      <div class="spot-edit-body container-fluid">
        <%= form_with model: @spot, local: true do |f| %>
          <%= render "shared/error_messages", resource: @spot %>

          <div class="field row">
            <%= f.label :title, class: "required" %></br>
            <div class="field-content row">
              <div class="field-content-left">
                <i class="fa-regular fa-flag"></i>
              </div>
              <div class="field-content-right">
                <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "field-content-title", placeholder: "タイトルを入力してください" %>
              </div>
            </div>
            <p>※15文字以内ご入力してください</p>
          </div>

          <div class="field row">
            <%= f.label :address, class: "required spot-edit-image" %></br>
            <div class="field-content row">
              <div class="field-content-left">
                <i class="fa-solid fa-location-dot"></i>
              </div>
              <div class="field-content-right">
                <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "field-content-address", placeholder: "住所を入力してください" %>
              </div>
            </div>
          </div>

          <div class="field row">
            <%= f.label :content %></br>
            <%= f.text_area :content, autocomplete: "content", class: "field-content field-spot-content", placeholder: "スポットに対する感想などを入力してください" %>
            <p>※150文字以内入力してください</p>
          </div>

          <div class="field row">
            <%= f.label :spot_image, class: "required" %></br>
            <div  class="spot-edit-image">
              <%= image_tag @spot.spot_image, alt: "ポストイメージ画像" if @spot.spot_image.present? %>
            </div>
            <div class="spot-edit-image-content"><%= f.file_field :spot_image, autocomplete: "spot_image" %></div>
          </div>

          <div class="field row">
            <%= f.label :category, "カテゴリ" %>
              <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
                <%= category.label do %>
                <%= category.check_box %>
                <%= category.text %>
              <% end %>
            <% end %>
          </div>

          <%= f.hidden_field :user_id, value: current_user.id %>

          <div class="row">
            <div class="form-btn"><%= f.submit "投稿する", class: "btn btn-primary" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spots/index.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "スポット一覧", spots_path %></li>
    </ol>
  </nav>
  <div class="spots-title">
    <h1>Spots</h1>
    <p>スポット一覧</p>
  </div>
  <div class="spot-search">
    <div class="spot-search-form">
      <%= search_form_for @q, url: spots_path do |f| %>
        <div class="search-form-area">
          <i class="fa-solid fa-magnifying-glass"></i>
          <%= f.search_field :address_cont, class: "search-content", placeholder: "住所検索ワード 例)都道府県名、市町村、etc..." %>
        </div>
        <div class="search-form-btn">
          <%= f.submit '検索', class: "btn btn-primary search-btn" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="spots">
    <div class="nav-side">
      <ul class="nav-side-content">
        <li><%= link_to "新規投稿", new_spot_path, class: "nav-side-item" %></li>
        <li class="nav-side-item">
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              カテゴリー
            </button>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li>
                  <%= link_to spots_path(category_id: category.id), class: "dropdown-item" do %>
                    <%= category.name %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </li>
      </ul>
    </div>
    <% if @spots.blank? %>
      <div class="spots-text-zero">
        <p>投稿がありません</p>
      </div>
    <% else %>
      <div class="spots-contents">
        <% @spots.each do | spot | %>
          <%= link_to spot_path(spot) do %>
            <div class="spot-content scale">
              <div class="spot-top">
                <div class="spot-content-image">
                  <%= image_tag spot.spot_image, class: "spot-image", alt: "スポットイメージ画像" if spot.spot_image.present? %>
                </div>
              </div>
              <div class="spot-down">
                <ul>
                  <li class="spot-title">
                    <p><%= spot.title %></p>
                  </li>
                  <li class="spot-address">
                    <i class="fa-solid fa-location-dot"></i>
                    <p><%= spot.address %></p>
                  </li>
                  <li class="spot-category">
                    <i class="fa-solid fa-house"></i>
                    <% spot.categories.each do |category| %>
                      <p><%= category.name %></p>
                      <p><%= "," %></p>
                    <% end %>
                  </li>
              </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
    <%= paginate @spots, class: "page" %>
</div>

app/views/spots/new.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "投稿一覧", spots_path %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "スポット新規", new_spot_path %></li>
    </ol>
  </nav>
  <div class="spot-new">
    <div class="spot-new-title">
      <h1>New Spot</h1>
      <p>スポット新規投稿</p>
    </div>
    <div class="spot-new-form">
      <div class="spot-new-body container-fluid">
        <%= form_with model: @spot, local: true do |f| %>
          <%= render "shared/error_messages", resource: @spot %>

          <div class="field row">
            <%= f.label :title, class: "required" %></br>
            <div class="field-content row">
              <div class="field-content-left">
                <i class="fa-regular fa-flag"></i>
              </div>
              <div class="field-content-right">
                <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "field-content-title", placeholder: "タイトルを入力してください" %>
              </div>
            </div>
            <p>※15文字以内ご入力してください</p>
          </div>

          <div class="field row">
            <%= f.label :address, class: "required" %></br>
            <div class="field-content row">
              <div class="field-content-left">
                <i class="fa-solid fa-location-dot"></i>
              </div>
              <div class="field-content-right">
                <%= f.text_field :address, autofocus: true, autocomplete: "address", class: "field-content-address", placeholder: "住所を入力してください" %>
              </div>
            </div>
          </div>

          <div class="field row">
            <%= f.label :content %></br>
            <%= f.text_area :content, autocomplete: "content", class: "field-content field-spot-content", placeholder: "スポットに対する感想などを入力してください" %>
            <p>※150文字以内入力してください</p>
          </div>

          <div class="field row">
            <%= f.label :spot_image, class: "required" %></br>
            <div class="spot-new-image-content"><%= f.file_field :spot_image, autocomplete: "spot_image" %></div>
          </div>

          <div class="field row">
            <%= f.label :category %>
              <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
                <%= category.label do %>
                <%= category.check_box %>
                <%= category.text %>
              <% end %>
            <% end %>
          </div>

          <%= f.hidden_field :user_id, value: current_user.id %>

          <div class="row">
            <div class="form-btn"><%= f.submit "投稿する", class: "btn btn-primary" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spots/show.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "投稿一覧", spots_path %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "スポット投稿", spot_path(@spot) %></li>
    </ol>
  </nav>
  <div class="show-spot-title">
    <h1>spot</h1>
    <p>スポット投稿</p>
  </div>
    <div class="show-spot-content">
      <div class="show-spot-top">
        <div class="show-spot-content-image">
          <%= image_tag @spot.spot_image, class: "show-spot-image", alt: "スポットイメージ画像" if @spot.spot_image.present? %>
        </div>
      </div>
      <div class="show-spot-down">
        <ul>
          <li class="show-spot-content-title"><%= @spot.title %></li>
          <li class="show-spot-content-address">
            <i class="fa-solid fa-location-dot"></i>
            <%= @spot.address %>
          </li>
          <li class="show-spot-content-category">
            <i class="fa-solid fa-house"></i>
            <% @spot.categories.each do |category| %>
              <%= category.name %>
              <%= "," %>
            <% end %>
          </li>
          <li class="show-spot-content-content"><%= @spot.content %></li>
          <% if current_user.id == @spot.user_id %>
            <div class="show-spot-content-edit">
              <li class="spot-edit">
                <%= link_to edit_spot_path do %>
                  <span class="fa-solid fa-pen-to-square"></span>
                <% end %>
              </li>
              <li class="spot-delete">
                <%= link_to spot_path(@spot), method: :delete, data: { confirm: "投稿内容を本当に削除しますか？" } do %>
                  <span class="fa-solid fa-trash-can"></span>
                <% end %>
              </li>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
    <%= render "shared/spot_map" %>
  </div>
</div>