config/routes.rb
Rails.application.routes.draw do

# ============== spots ======================
  resources :spots
# ============== spots ======================

# ============== posts ======================
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
# ============== posts ======================

# ============== users ======================
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
    post 'users/guest_login', to: 'users/sessions#guest_login'
  end

  resources :users do
    member do
      get 'profile'
    end
  end
# ============== users ======================
  root to: 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  # イメージカラムを指定
  has_one_attached :image

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  #アソシエーション設定
  has_many :posts, dependent: :destroy
  has_many :spots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :gender, presence: true, on: :update
  validates :introduction, length: { maximum: 150 }
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。"
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーの更新・削除はできません。"
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_login
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.with_attached_image.includes(:posts, :spots).page(params[:page]).per(15).order(created_at: :desc)
  end

  def profile
    @user = User.includes(posts: [:likes], spots: [:categories]).find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.image.nil?
      @user.image = "default.png"
    end
    if @user.update(user_params)
      flash[:notice] = "#{@user.name}の情報を更新しました"
      redirect_to profile_user_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to users_path
    flash[:notice] = "#{@user.name}のアカウントを削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :gender, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "ユーザー", users_path %></li>
      <li class="breadcrumb-item"><%= link_to "プロフィール", user_path(@user) %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "プロフィール編集", edit_user_path %></li>
    </ol>
  </nav>
  <div class="profile-edit">
    <div class="profile-edit-title">
      <h1>Edit Profile</h1>
      <p>プロフィール編集</p>
    </div>
    <div class="profile-edit-form">
      <div class="user-icon-item">
        <% if current_user.image.present? %>
          <div class="user-icon">
            <%= image_tag current_user.image, alt: "ユーザー画像" %>
          </div>
        <% else %>
          <div class="user-icon">
            <%= image_tag "default.png", alt: "ゲスト画像" %>
          </div>
        <% end %>
      </div>
      <div class="profile-edit-body container-fluid">
        <%= form_with model: @user, local: true do |f| %>
          <%= render "shared/error_messages", resource: @user %>

          <div class="field row">
            <%= f.label :name, class: "required" %></br>
            <div class="field-content row">
              <div class="field-content-left">
                <i class="fa-regular fa-face-smile size"></i>
              </div>
              <div class="field-content-right">
                <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "field-content-name", placeholder: "ユーザー名を入力してください" %>
              </div>
            </div>
          </div>

          <div class="field row">
            <%= f.label :image %></br>
            <div  class="profile-edit-image">
              <%= image_tag @user.image, alt: "ユーザー画像" if @user.image.present? %>
            </div>
            <div class="profile-edit-image-content"><%= f.file_field :image, autocomplete: "image" %></div>
          </div>

          <div class="field row">
            <%= f.label :gender, class: "required profile-edit-gender" %></br>
            <div class="radio-botton">
              <%= f.radio_button :gender, :男性 %>
              <%= f.label :gender, "男性", {value: :男性, style: "display: inline-block;", class: "radio-label"} %>
              <%= f.radio_button :gender, :女性 %>
              <%= f.label :gender, "女性", {value: :女性, style: "display: inline-block;", class: "radio-label"} %>
            </div>
          </div>

          <div class="field row">
            <%= f.label :introduction %></br>
            <%= f.text_area :introduction, autocomplete: "introduction", class: "field-content field-introduction", placeholder: "初めまして、マミーです。よろしくお願いします" %>
            <p>※150文字以内入力してください</p>
          </div>

          <div class="row">
            <div class="form-btn"><%= f.submit "更新する", class: "profile-edit-btn btn btn-primary" %></div>
          </div>
        <% end %>
      </div>
      <div class="profile-edit-footer">
        <%= link_to "戻る", :back %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "ユーザー(一覧)", users_path %></li>
    </ol>
  </nav>
  <div class="users-title">
    <h1>Users</h1>
    <p>ユーザー一覧</p>
  </div>
  <div class="users-contents">
    <% @users.each do | user | %>
      <%= link_to profile_user_path(id: user) do %>
        <div class="users-content scale">
          <div class="users-left">
            <div class="user-icon">
              <% if user.image.present? %>
                <%= image_tag user.image, alt: "ユーザー画像" %>
              <% else %>
                <%= image_tag "default.png", alt: "ゲスト画像" %>
              <% end %>
            </div>
          </div>
          <div class="users-right">
            <ul class="users-top">
              <li class="user-name">
                <%= user.name %>
              </li>
              <li class="user-posts"><p><%= "Post: #{user.posts.size}" %></p></li>
              <li class="user-places"><%= "Spot: #{user.spots.size}" %></p></li>
              <% if user.gender %>
                <li class="user-gender">
                  <% case user.gender %>
                    <% when "男性" %>
                      <span class="fa-solid fa-person fa-bounce man"></span>
                    <% when "女性" %>
                      <span class="fa-solid fa-person-dress fa-bounce woman"></span>
                  <% end %>
                </li>
              <% end %>
            </ul>
            <div class="users-down">
              <% if user.introduction %>
                <%= user.introduction %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= paginate @users, class: "page" %>
</div>

app/views/users/profile.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "ユーザー", users_path %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= link_to "プロフィール", user_path(@user) %></li>
    </ol>
  </nav>
  <div class="user-title">
    <h1>User</h1>
    <p>ユーザー</p>
  </div>
  <div class="user-form">
    <div class="user-top">
      <div class="user-icon">
        <% if @user.image.present? %>
          <%= image_tag @user.image, alt: "ユーザー画像" %>
        <% else %>
          <%= image_tag "default.png", class: "guest-user", alt: "ゲスト画像" %>
        <% end %>
      </div>
      <div class="user-name">
        <% if @user.name? %>
          <h2><%= @user.name %></h2>
        <% else %>
          <h2>ゲスト</h2>
        <% end %>
      </div>
      <div class="user-posts"><p><%= "Post: #{@user.posts.size}" %></p></div>
      <div class="user-places"><%= "Spot: #{@user.spots.size}" %></p></div>
      <div class="user-gender">
        <% case @user.gender %>
          <% when "男性" %>
            <span class="fa-solid fa-person fa-bounce man"></span>
          <% when "女性" %>
            <span class="fa-solid fa-person-dress fa-bounce woman"></span>
        <% end %>
      </div>
    </div>
    <div class="user-down">
      <div class="user-introduction">
        <% if @user.introduction? %>
          <%= @user.introduction %>
        <% else %>
          <%= render "shared/user_introduction_exmple" %>
        <% end %>
      </div>
    </div>
    <% if current_user.id == @user.id %>
      <% unless @user.name == "ゲスト" %>
        <div class="user-links">
          <%= link_to "プロフィール編集", edit_user_path, class: "user-edit" %>
          <%= link_to "アカウント編集", edit_user_registration_path, class: "user-edit" %>
          <%= link_to "アカウントを削除", profile_user_path(id: @user), method: :delete, data: { confirm: "ユーザーのアカウントを本当に削除しますか？" }, class: "user-delete" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="posts-title">
    <h1>Posts</h1>
    <p>投稿一覧</p>
  </div>
  <div class="posts-contents">
    <div class="posts-text-zero">
      <% if @user.posts.blank? %>
        <p>投稿がありません</p>
      <% end %>
    </div>
    <% @user.posts.each do |posts| %>
      <%= link_to post_path(id: posts) do %>
        <div class="posts-content scale">
          <div class="posts-left">
            <div class="user-icon">
              <% if posts.user.image.present? %>
                <%= image_tag posts.user.image, alt: "ユーザー画像" %>
              <% else %>
                <%= image_tag "default.png", alt: "ゲスト画像" %>
              <% end %>
            </div>
          </div>
          <div class="posts-right">
            <div class="posts-top">
              <div class="posts-top-right">
                <div class="user-name">
                  <p><%= posts.user.name %></p>
                </div>
              </div>
              <div class="posts-top-left">
                <div class="post-user-create-time">
                  作成日: <%= posts.created_at.to_s(:datetime_jp) %>
                </div>
              </div>
            </div>
            <div class="posts-main">
              <div class="posts-content-image">
                <% if posts.post_image.present? %>
                  <%= image_tag posts.post_image, alt: "ポストイメージ画像" %>
                <% end %>
              </div>
              <div class="posts-content-item">
                <% if posts.content %>
                  <%= posts.content %>
                <% end %>
              </div>
            </div>
            <ul class="posts-down">
              <% if current_user.id == posts.user_id %>
                <li class="post-like">
                  <% if posts.liked?(posts.likes, current_user.id) %>
                    <span class="fa fa-heart liked-btn"></span>
                  <% else %>
                    <span class="fa-regular fa-heart"></span>
                  <% end %>
                  <%= posts.likes.size %>
                </li>
              <% else %>
                <% if user_signed_in? %>
                  <li class="post-like">
                    <% if posts.liked?(posts.likes, current_user.id) %>
                      <%= link_to post_likes_path(posts), method: :delete do %>
                        <span class="fa fa-heart liked-btn"></span>
                      <% end %>
                    <% else %>
                      <%= link_to post_likes_path(posts), method: :post do %>
                        <span class="fa-regular fa-heart"></span>
                      <% end %>
                    <% end %>
                    <%= posts.likes.size %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="spots-title">
    <h1>Spots</h1>
    <p>スポット一覧</p>
  </div>
  <div class="user-spots">
    <% if @user.posts.blank? %>
      <div class="posts-text-zero">
        <p>投稿がありません</p>
      </div>
    <% else %>
      <div class="user-spots-contents">
        <% @user.spots.each do | spot | %>
          <%= link_to spot_path(spot) do %>
            <div class="spot-content scale">
              <div class="spot-top">
                <div class="spot-content-image">
                  <%= image_tag spot.spot_image, class: "spot-image", alt: "スポットイメージ画像" if spot.spot_image.present? %>
                </div>
              </div>
              <div class="spot-down">
                <ul>
                  <li class="spot-title">
                    <p><%= spot.title %></p>
                  </li>
                  <li class="spot-address">
                    <i class="fa-solid fa-location-dot"></i>
                    <p><%= spot.address %></p>
                  </li>
                  <li class="spot-category">
                    <i class="fa-solid fa-house"></i>
                    <% spot.categories.each do |category| %>
                      <%= category.name %>
                      <%= "," %>
                    <% end %>
                  </li>
              </ul>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>