config/routes.rb
Rails.application.routes.draw do

# ============== spots ======================
  resources :spots
# ============== spots ======================

# ============== posts ======================
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
# ============== posts ======================

# ============== users ======================
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
    post 'users/guest_login', to: 'users/sessions#guest_login'
  end

  resources :users do
    member do
      get 'profile'
    end
  end
# ============== users ======================
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :spot_category_relations
  has_many :spots, through: :spot_category_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  #アソシエーション設定
  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: { maximum: 500 }
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  #アソシエーション設定
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  # イメージカラムを指定
  has_one_attached :post_image

  #アソシエーション設定
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 「ログイン中のユーザーがその投稿に対していいねをしているか」
  # def liked?(user)
  #   likes.where(user_id: user.id).present?
  # end
  def liked?(like, current_user_id)
    like.pluck(:user_id).include?(current_user_id)
  end

  # ransackモデルにホワイトリストを登録
  def self.ransackable_attributes(auth_object = nil)
    ["content"]
  end

  validates :content, presence: true, length: { maximum: 500 }
  validates :user_id, presence: true
end

app/models/spot.rb
class Spot < ApplicationRecord
  # イメージカラムを指定
  has_one_attached :spot_image

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  #アソシエーション設定
  belongs_to :user
  has_many :spot_category_relations
  has_many :categories, through: :spot_category_relations

  # ransackモデルにホワイトリストを登録
  def self.ransackable_attributes(auth_object = nil)
    ["address"]
  end

  validates :title, presence: true, length: { maximum: 15 }
  validates :address, presence: true
  validates :spot_image, presence: true
  validates :content, length: { maximum: 150 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  # イメージカラムを指定
  has_one_attached :image

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  #アソシエーション設定
  has_many :posts, dependent: :destroy
  has_many :spots, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :gender, presence: true, on: :update
  validates :introduction, length: { maximum: 150 }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(user_id: current_user.id, post_id: params[:post_id])
    @like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q, only: [:index]

  def index
    @results = @q.result.with_attached_post_image.includes(:likes, :user, :comments).page(params[:page]).per(15).order(created_at: :desc)
  end

  def show
    @post = Post.preload(:likes, :user, :comments).find(params[:id])
    @likes = @post.likes
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "#{@post.user.name}さんの投稿が完了しました。"
      redirect_to posts_path
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "#{@post.user.name}さんの投稿を更新しました"
      redirect_to posts_path
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
    flash[:notice] = "#{@post.user.name}さんの投稿を削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :post_image)
  end

  def set_q
    @q = Post.ransack(params[:q])
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q, only: [:index]

  def index
    @spots = @q.result.with_attached_spot_image.includes(:categories, :spot_category_relations).page(params[:page]).per(12).order(created_at: :desc)
    @categories = Category.all
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @spots = @category.spots.page(params[:page]).per(12).order(created_at: :desc)
    end
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      flash[:notice] = "#{@spot.user.name}さんのスポット投稿が完了しました。"
      redirect_to spots_path
    else
      render "new"
    end
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      flash[:notice] = "#{@spot.user.name}さんの投稿を更新しました"
      redirect_to spots_path
    else
      render "edit"
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to spots_path
    flash[:notice] = "#{@spot.user.name}さんの投稿を削除しました"
  end

  private

  def spot_params
    params.require(:spot).permit(:title, :content, :address, :latitude, :longitude, :spot_image, :user_id, category_ids: [])
  end

  def set_q
    @q = Spot.ransack(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.with_attached_image.includes(:posts, :spots).page(params[:page]).per(15).order(created_at: :desc)
  end

  def profile
    @user = User.includes(posts: [:likes], spots: [:categories]).find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.image.nil?
      @user.image = "default.png"
    end
    if @user.update(user_params)
      flash[:notice] = "#{@user.name}の情報を更新しました"
      redirect_to profile_user_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to users_path
    flash[:notice] = "#{@user.name}のアカウントを削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :gender, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Mammiiiiii(マミー)"
    page_title.blank? ? base_title : "#{page_title} - #{base_title}"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- GOOGLE FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <!-- GOOGLE FONTS -->

    <!-- BOOTSTRAP -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    >
    <!-- BOOTSTRAP -->

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= render "shared/flash", class: "flash" %>
      <%= yield %>
    <%= render "shared/footer" %>

    <!-- BOOTSTRAP -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></script>
    <!-- BOOTSTRAP -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger">
    <%= alert %>
  </p>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="footer-logo">
      <%= link_to root_path do %>
        <h1><span>M</span>ammiiiiii</h1>
        <p>( マミー )</p>
      <% end %>
    </div>
    <p class="copyright">&copy; <%= Time.current.year %> Mammiiiiii - brothers </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <span>M</span>ammiiiiii
      <% end %>
      <div class="collapse navbar-collapse" id="exampleNavbarToggle">
        <ul class="navbar-nav me-auto mb-2">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Posts", posts_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Spots", spots_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Logout", logout_path, method: :delete, class: "nav-link text-white" %></li>
            <li class="nav-item">
              <% if current_user.name? %>
                <%= link_to current_user.name, profile_user_path(id: current_user), class: "nav-link text-white" %>
              <% else %>
                <%= link_to "ゲスト", profile_user_path(id: current_user), class: "nav-link text-white" %>
              <% end %>
            </li>
            <li class="nav-item">
              <div class="user-icon">
                <% if current_user.image.present? %>
                  <%= link_to profile_user_path(id: current_user), class: "nav-link" do %>
                    <%= image_tag current_user.image, alt: "ユーザー画像" %>
                  <% end %>
                <% else %>
                  <%= link_to profile_user_path(id: current_user), class: "nav-link" do %>
                    <%= image_tag "default.png", class: "guest-img", alt: "ゲスト画像" %>
                  <% end %>
                <% end %>
              </div>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to "Signup", new_user_registration_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Guest", users_guest_login_path, method: :post, class: "nav-link text-white" %></li>
          <% end %>
        </ul>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h3 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h3>
          <button class="btn-close text-reset" type="button" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav flex-grow-1 pe-3">
            <% if user_signed_in? %>
              <li class="nav-item"><i class="fa-solid fa-house fa-sm"></i><%= link_to "Home", root_path, class: "nav-link text-primary" %></li>
              <li class="nav-item"><i class="fa-solid fa-user"></i><%= link_to "Users", users_path, class: "nav-link text-primary" %></li>
              <li class="nav-item"><i class="fa-solid fa-paper-plane"></i><%= link_to "Posts", posts_path, class: "nav-link text-primary" %></li>
              <li class="nav-item"><i class="fa-solid fa-map-location-dot"></i><%= link_to "Spots", spots_path, class: "nav-link text-primary" %></li>
              <li class="nav-item"><i class="fa-solid fa-right-from-bracket"></i><%= link_to "Logout", logout_path, method: :delete, class: "nav-link text-primary" %></li>
            <% else %>
              <li class="nav-item"><i class="fa-solid fa-user-plus"></i><%= link_to "Signup", new_user_registration_path, class: "nav-link text-primary" %></li>
              <li class="nav-item"><i class="fa-solid fa-right-to-bracket"></i><%= link_to "Login", login_path, class: "nav-link text-primary" %></li>
              <li class="nav-item"><i class="fa-solid fa-person-circle-check"></i><%= link_to "Guest", users_guest_login_path, method: :post, class: "nav-link text-primary" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "既にアカウントをお持ちの方はログインへ", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録する", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_spot_map.html.erb
<div class="map">
  <div class="show-map-title">
    <h1>Map</h1>
    <p>マップで確認</p>
  </div>
  <script>
    function initMap() {
      var test = {lat: <%= @spot.latitude %>, lng: <%= @spot.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: test
        });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);
      var contentString = '住所：<%= @spot.address %>';
      var infowindow = new google.maps.InfoWindow({
        content: contentString
      });
      var marker = new google.maps.Marker({
        position:test,
        map: map,
        title: contentString
      });
      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
    }
  </script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap">
  </script>
  <div id="map"></div>
</div>

app/views/shared/_user_introduction_exmple.erb
<p class="user-introduction-exmple">例) 初めまして、20代後半で2児のパパです。<br>
  子育てに悩むことも多くいろんな方のご意見などを参考にしたいと思っております。<br>
  現在は、上の子がもう少しで小学校に入学するので子供の教育について興味があります。<br>
  よろしくお願いします。
</p>