config/routes.rb
Rails.application.routes.draw do

# ============== spots ======================
  resources :spots
# ============== spots ======================

# ============== posts ======================
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
# ============== posts ======================

# ============== users ======================
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
    post 'users/guest_login', to: 'users/sessions#guest_login'
  end

  resources :users do
    member do
      get 'profile'
    end
  end
# ============== users ======================
  root to: 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  # イメージカラムを指定
  has_one_attached :post_image

  #アソシエーション設定
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  # 「ログイン中のユーザーがその投稿に対していいねをしているか」
  # def liked?(user)
  #   likes.where(user_id: user.id).present?
  # end
  def liked?(like, current_user_id)
    like.pluck(:user_id).include?(current_user_id)
  end

  # ransackモデルにホワイトリストを登録
  def self.ransackable_attributes(auth_object = nil)
    ["content"]
  end

  validates :content, presence: true, length: { maximum: 500 }
  validates :user_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q, only: [:index]

  def index
    @results = @q.result.with_attached_post_image.includes(:likes, :user, :comments).page(params[:page]).per(15).order(created_at: :desc)
  end

  def show
    @post = Post.preload(:likes, :user, :comments).find(params[:id])
    @likes = @post.likes
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "#{@post.user.name}さんの投稿が完了しました。"
      redirect_to posts_path
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "#{@post.user.name}さんの投稿を更新しました"
      redirect_to posts_path
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
    flash[:notice] = "#{@post.user.name}さんの投稿を削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :post_image)
  end

  def set_q
    @q = Post.ransack(params[:q])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "投稿一覧", posts_path %></li>
      <li class="breadcrumb-item"><%= link_to "ユーザー投稿", post_path(@post) %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "投稿編集", edit_post_path %></li>
    </ol>
  </nav>
  <div class="post-edit">
    <div class="post-edit-title">
      <h1>Edit Post</h1>
      <p>投稿編集</p>
    </div>
    <div class="post-edit-form">
      <div class="post-edit-body container-fluid">
        <%= form_with model: @post, local: true do |f| %>
          <%= render "shared/error_messages", resource: @post %>

          <div class="field row">
            <%= f.label :content, class: "required" %></br>
            <%= f.text_area :content, autofocus: true, autocomplete: "content", class: "post-field-content", placeholder: "初めまして、マミーです。よろしくお願いします" %>
            <p>※500文字以内入力してください</p>
          </div>

          <div class="field row">
            <%= f.label :post_image %></br>
            <div class="post-edit-image">
              <%= image_tag @post.post_image, alt: "ポストイメージ画像" if @post.post_image? %>
            </div>
            <div class="post-edit-image-content"><%= f.file_field :post_image, autocomplete: "image" %></div>
          </div>

          <%= f.hidden_field :user_id, value: current_user.id %>

          <div class="row">
            <div class="form-btn"><%= f.submit "編集する", class: "btn btn-primary" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "投稿一覧", posts_path %></li>
    </ol>
  </nav>
  <div class="posts-title">
    <h1>Posts</h1>
    <p>投稿一覧</p>
  </div>
  <div class="posts-btn">
      <%= link_to new_post_path do %>
        <p class="posts-btn-TITLE">New Post</p>
        <p class="posts-btn-title">新規投稿</p>
      <% end %>
  </div>
  <div class="posts-contents">
    <div class="search">
      <div class="post-search-form">
        <%= search_form_for @q, url: posts_path do |f| %>
          <div class="search-form-area">
            <i class="fa-solid fa-magnifying-glass"></i>
            <%= f.search_field :content_cont, class: "search-content", placeholder: "投稿検索ワード" %>
          </div>
          <div class="search-form-btn">
            <%= f.submit '検索', class: "btn btn-primary search-btn" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="result-count">
      <h2><%= "検索結果：#{@results.size}" %></h2>
    </div>
    <div class="posts-text-zero">
      <% if @results.blank? %>
        <p>投稿がありません</p>
      <% end %>
    </div>
    <% @results.each do | post | %>
      <%= link_to post_path(post) do %>
        <div class="posts-content scale">
          <div class="posts-left">
            <div class="user-icon">
              <% if post.user.image.present? %>
                <%= image_tag post.user.image, alt: "ユーザー画像" %>
              <% else %>
                <%= image_tag "default.png", alt: "ゲスト画像" %>
              <% end %>
            </div>
          </div>
          <div class="posts-right">
            <div class="posts-top">
              <div class="posts-top-right">
                <div class="user-name">
                  <p><%= post.user.name %></p>
                </div>
                <div class="post-gender">
                  <% if post.user.gender %>
                    <% case post.user.gender %>
                      <% when "男性" %>
                        <span class="fa-solid fa-person fa-bounce man"></span>
                      <% when "女性" %>
                        <span class="fa-solid fa-person-dress fa-bounce woman"></span>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="posts-top-left">
                <div class="post-user-create-time">
                  作成日: <%= post.created_at.to_s(:datetime_jp) %>
                </div>
              </div>
            </div>
            <div class="posts-main">
              <div class="posts-content-image">
                <% if post.post_image.present? %>
                  <%= image_tag post.post_image, class: "post-image", alt: "ポストイメージ画像" %>
                <% end %>
              </div>
              <div class="posts-content-item">
                <% if post.content %>
                  <%= post.content %>
                <% end %>
              </div>
            </div>
            <ul class="posts-down">
              <li class="post-comment">
                <span class="fa-regular fa-comments"></span>
                <%= post.comments.size %>
              </li>
              <li class="post-like">
                <% if user_signed_in? %>
                  <% if post.liked?(post.likes, current_user.id) %>
                    <span class="fa fa-heart liked-btn"></span>
                  <% else %>
                    <span class="fa-regular fa-heart"></span>
                  <% end %>
                  <%= post.likes.size %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= paginate @results, class: "page" %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "投稿一覧", posts_path %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "新規投稿", new_post_path %></li>
    </ol>
  </nav>
  <div class="post-new">
    <div class="post-new-title">
      <h1>New Post</h1>
      <p>新規投稿</p>
    </div>
    <div class="post-new-form">
      <div class="post-new-body container-fluid">
        <%= form_with model: @post, local: true do |f| %>
          <%= render "shared/error_messages", resource: @post %>

          <div class="field row">
            <%= f.label :content, class: "required" %></br>
            <%= f.text_area :content, autofocus: true, autocomplete: "content", class: "post-field-content", placeholder: "子育てに関する感想や疑問などを投稿しましょう。" %>
            <p>※500文字以内入力してください</p>
          </div>

          <div class="field row">
            <%= f.label :post_image, class: "post-new-image" %></br>
            <div class="post-new-image-content"><%= f.file_field :post_image, autocomplete: "image" %></div>
          </div>

          <%= f.hidden_field :user_id, value: current_user.id %>

          <div class="row">
            <div class="form-btn"><%= f.submit "投稿する", class: "btn btn-primary" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to "ホーム", root_path %></li>
      <li class="breadcrumb-item"><%= link_to "投稿一覧", posts_path %></li>
      <li class="breadcrumb-item active"  aria-current="page"><%= link_to "ユーザー投稿", post_path(@post) %></li>
    </ol>
  </nav>
  <div class="post-title">
    <h1>Post</h1>
    <p>投稿</p>
  </div>
  <div class="post">
    <div class="post-content">
      <div class="post-left">
        <div class="user-icon">
          <% if @post.user.image.present?  %>
            <%= image_tag @post.user.image, alt: "ユーザー画像" %>
          <% else %>
            <%= image_tag "default.png", alt: "ゲスト画像" %>
          <% end %>
        </div>
      </div>
      <div class="post-right">
        <div class="post-top">
          <div class="post-top-left">
            <div class="post-name">
              <%= @post.user.name %>
            </div>
            <div class="post-gender">
              <% if @post.user.gender? %>
                <% case @post.user.gender %>
                  <% when "男性" %>
                    <span class="fa-solid fa-person fa-bounce man"></span>
                  <% when "女性" %>
                    <span class="fa-solid fa-person-dress fa-bounce woman"></span>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="post-top-right">
            <div class="post-create-time">
              作成日: <%= @post.created_at.to_s(:datetime_jp) %>
            </div>
          </div>
        </div>
        <div class="posts-main">
          <div class="posts-content-image">
            <% if @post.post_image.present? %>
              <%= image_tag @post.post_image, class: "post-image", alt: "ポストイメージ画像" %>
            <% end %>
          </div>
          <div class="posts-content-item">
            <%= @post.content %>
          </div>
        </div>
        <ul class="post-down">
          <% if current_user.id == @post.user_id %>
            <li class="post-comment">
              <span class="fa-regular fa-comments"></span>
              <%= @post.comments.size %>
            </li>
            <li class="post-like">
              <% if @post.likes.size == 0 %>
                  <span class="fa-regular fa-heart"></span>
              <% else %>
                  <span class="fa fa-heart liked-btn"></span>
              <% end %>
              <%= @post.likes.size %>
            </li>
            <li class="post-edit">
              <%= link_to edit_post_path do %>
                <span class="fa-solid fa-pen-to-square"></span>
              <% end %>
            </li>
            <li class="post-delete">
              <%= link_to post_path(@post), method: :delete, data: { confirm: "投稿内容を本当に削除しますか？" } do %>
                <span class="fa-solid fa-trash-can"></span>
              <% end %>
            </li>
          <% else %>
            <% if user_signed_in? %>
              <li class="post-comment">
                <span class="fa-regular fa-comments"></span>
                <%= @post.comments.size %>
              </li>
              <li class="post-like">
                <% if @post.liked?(@post.likes, current_user.id) %>
                  <%= link_to post_like_path(@post), method: :delete do %>
                    <span class="fa fa-heart liked-btn"></span>
                  <% end %>
                <% else %>
                  <%= link_to post_likes_path(@post), method: :post do %>
                    <span class="fa-regular fa-heart"></span>
                  <% end %>
                <% end %>
                <%= @post.likes.size %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="comment">
    <div class="comment-contents">
      <div class="comment-post">
        <%= form_with model:[@post, @comment], local: true do |f| %>
          <div class="comment-text">
            <%= f.text_area :content, placeholder: "上記の投稿に対してコメントする..." %>
          </div>
          <div class="comment-text-btn">
            <%= f.submit "コメントする", class: "btn btn-primary" %>
          </div>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :post_id, value: @post.id %>
        <% end %>
      </div>
      <div class="comment-index">
        <% @comments.each do |comment| %>
          <div class="comment-content">
            <div class="comment-left">
              <% if comment.user.image.present? %>
                <div class="user-icon">
                  <%= image_tag comment.user.image, alt: "ユーザー画像" %>
                </div>
              <% else %>
                <div class="user-icon">
                  <%= image_tag "default.png", alt: "ゲスト画像" %>
                </div>
              <% end %>
            </div>
            <div class="comment-right">
              <div class="comment-top">
                <div class="comment-top-right">
                  <div class="user-name">
                    <p><%= comment.user.name %></p>
                  </div>
                </div>
                <div class="posts-top-left">
                  <div class="post-user-create-time">
                    <p>作成日: <%= comment.created_at.to_s(:datetime_jp) %></p>
                  </div>
                </div>
              </div>
              <div class="comment-main">
                <%= comment.content %>
              </div>
              <ul class="post-down">
                <% if current_user.id == comment.user_id %>
                  <li class="post-delete">
                    <%= link_to post_comment_path(comment.post,comment), method: :delete, data: { confirm: "#{comment.user.name}さんコメント内容を本当に削除しますか？" } do %>
                      <span class="fa-solid fa-trash-can"></span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>